# Generated by Django 4.2.13 on 2024-06-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
